#
# Module manifest for module 'LithnetRMAutomation'
#
# Generated by: Ryan Newington
#
# Generated on: 04/08/2015
#

@{

# Version number of this module.
ModuleVersion = '2.0.0'

# ID used to uniquely identify this module
GUID = 'd7c36446-aca6-418a-a2a3-cbfc32016a52'

# Author of this module
Author = 'Ryan Newington'

# Company or vendor of this module
CompanyName = 'Lithnet'

# Copyright statement for this module
Copyright = 'Copyright (c) 2026 Lithnet Pty Ltd'

# Description of the functionality provided by this module
Description = 'PowerShell module for managing resources in the Microsoft Identity Manager (MIM) and Forefront Identity Manager (FIM) service. Runs on Windows PowerShell 5.1 and PowerShell 7.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = 'None'

# Supported PowerShell editions
CompatiblePSEditions = @('Desktop', 'Core')

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
#RequiredAssemblies = ''

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Root module that bootstraps assembly resolution before loading the binary module
RootModule = 'LithnetRMA.psm1'

# Functions to export from this module
FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @(
    'Get-ApprovalRequest',
    'Get-Resource',
    'Get-ResourceCount',
    'Import-RMConfig',
    'New-Resource',
    'New-ResourceUpdateTemplate',
    'New-XPathExpression',
    'New-XPathQuery',
    'New-XPathQueryGroup',
    'Remove-Resource',
    'Save-Resource',
    'Search-Resources',
    'Search-ResourcesPaged',
    'Set-PendingApprovalRequest',
    'Set-ResourceManagementClient',
    'Update-ResourceManagementClientSchema'
)

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('MIM', 'FIM', 'MicrosoftIdentityManager', 'ForefrontIdentityManager', 'IdentityManagement', 'ResourceManagement')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/lithnet/resourcemanagement-powershell/blob/master/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/lithnet/resourcemanagement-powershell'

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/lithnet/resourcemanagement-powershell/releases'
    }
}
}